import type { Drink, User } from '@/lib/types';

export const drinks: Drink[] = [
  {
    id: '1',
    name: 'Espresso',
    description: 'A concentrated coffee beverage brewed by forcing a small amount of nearly boiling water under pressure through finely-ground coffee beans.',
    ingredients: ['Coffee Beans', 'Water'],
    price: 150,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'espresso shot',
  },
  {
    id: '2',
    name: 'Cappuccino',
    description: 'An espresso-based coffee drink that originated in Italy, and is traditionally prepared with steamed milk foam.',
    ingredients: ['Espresso', 'Steamed Milk', 'Milk Foam'],
    price: 250,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'cappuccino art',
  },
  {
    id: '3',
    name: 'Latte',
    description: 'A coffee drink of Italian origin made with espresso and steamed milk.',
    ingredients: ['Espresso', 'Steamed Milk'],
    price: 250,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'latte art',
  },
  {
    id: '4',
    name: 'Americano',
    description: 'A type of coffee drink prepared by diluting an espresso with hot water, giving it a similar strength to, but different flavor from, traditionally brewed coffee.',
    ingredients: ['Espresso', 'Hot Water'],
    price: 200,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'americano coffee',
  },
  {
    id: '5',
    name: 'Raf Coffee',
    description: 'A coffee drink popular in Russia, prepared by adding cream and vanilla sugar to a single shot of espresso and then foaming it with a steam wand.',
    ingredients: ['Espresso', 'Cream', 'Vanilla Sugar'],
    price: 300,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'creamy coffee',
  },
  {
    id: '6',
    name: 'Matcha Latte',
    description: 'A sweet and creamy drink made with matcha powder, hot water, and milk.',
    ingredients: ['Matcha Powder', 'Hot Water', 'Milk'],
    price: 350,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'matcha latte',
  },
];

export const users: User[] = [
  {
    id: '1',
    name: 'Alexey K.',
    phone: '79991234567',
    role: 'customer',
    loyaltyTier: 'Coffee Guest',
    loyaltyPercentage: 5,
    bonusBalance: 125,
  },
  {
    id: '2',
    name: 'Ivan S.',
    phone: '79997654321',
    role: 'customer',
    loyaltyTier: 'SVO Participant',
    loyaltyPercentage: 10,
    bonusBalance: 450,
  },
  {
    id: '3',
    name: 'Maria B.',
    phone: '79111112233',
    role: 'admin',
    ordersCompleted: 137,
  },
    {
    id: '5',
    name: 'Olga V.',
    phone: '79114445566',
    role: 'admin',
    ordersCompleted: 89,
  },
  {
    id: '4',
    name: 'Dmitry P.',
    phone: '79223334455',
    role: 'owner',
  },
];
